CREATE TABLE IF NOT EXISTS contacts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(64) NULL,
  reason VARCHAR(120) NULL,
  message TEXT NOT NULL,
  meta JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS applications (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  reference_id VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(255) NULL,
  cnic VARCHAR(32) NULL,
  phone VARCHAR(64) NULL,
  city VARCHAR(120) NULL,
  product_mode VARCHAR(32) NULL,
  product_type VARCHAR(64) NULL,
  amount DECIMAL(14, 2) NULL,
  tenor INT NULL,
  purpose TEXT NULL,
  sector VARCHAR(120) NULL,
  monthly_income DECIMAL(14, 2) NULL,
  employment VARCHAR(64) NULL,
  consent TINYINT(1) NOT NULL DEFAULT 0,
  meta JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
